import './featureSection.scss';

import SearchFeatureImage from '../../Assets/Images/search-feature.svg';
import SelectFeature from '../../Assets/Images/select-feature.svg';
import StandoutFeature from '../../Assets/Images/standout-feature.svg';

function FeaturesSection() {
  return (
    <div className='d-feature'>
      <div className='d-container'>
        <div className='d-feature__images d-feature__wrap'>
          <div>
            <img src={SearchFeatureImage} style={{ width: '50px' }} />
            <h5>Search</h5>
            <p>Simply add a keyword or a term related to your business in the slogan maker search box. Wait for the magic to happen.</p>
          </div>
          <div>
            <img src={SelectFeature} style={{ width: '55px' }} />
            <h5>Select</h5>
            <p>Choose from thousands of options generated by the slogan maker that fit your needs.</p>
          </div>
          <div>
            <img src={StandoutFeature} />
            <h5>Stand out</h5>
            <p>Congrats on your new slogan. It's time to win the world!</p>
          </div>
        </div>
      </div>
    </div>
  );
}

export default FeaturesSection;
