import './featureSection.scss';

function FeaturesSection() {
  return (
    <div className='d-feature'>
      <div className='d-container'>
        <div className='row d-feature__images'>
          <div className='col-sm-4'>
            <svg width='52' height='52' viewBox='0 0 52 52' fill='none' xmlns='http://www.w3.org/2000/svg'>
              <path
                d='M44.6667 2H7.33333C4.38781 2 2 4.38781 2 7.33333V44.6667C2 47.6122 4.38781 50 7.33333 50H44.6667C47.6122 50 50 47.6122 50 44.6667V7.33333C50 4.38781 47.6122 2 44.6667 2Z'
                fill='#146EB4'
                fill-opacity='0.15'
                stroke='#146EB4'
                stroke-width='3.5'
                stroke-miterlimit='10'
              />
              <path d='M2 18H50' stroke='#146EB4' stroke-width='3.5' stroke-miterlimit='10' />
              <path d='M18 50V18' stroke='#146EB4' stroke-width='3.5' stroke-miterlimit='10' />
            </svg>
          </div>
          <div className='col-sm-4'>
            <svg width='60' height='52' viewBox='0 0 60 52' fill='none' xmlns='http://www.w3.org/2000/svg'>
              <rect
                x='2'
                y='2'
                width='56'
                height='48'
                rx='5'
                fill='#146EB4'
                fill-opacity='0.15'
                stroke='#146EB4'
                stroke-width='3.5'
                stroke-miterlimit='10'
              />
              <path
                d='M20 17L28.3324 37L31.2905 28.2905L40 25.3324L20 17Z'
                stroke='#146EB4'
                stroke-width='3.5'
                stroke-linecap='round'
                stroke-linejoin='round'
              />
            </svg>
          </div>
          <div className='col-sm-4'>
            <svg width='72' height='72' viewBox='0 0 72 72' fill='none' xmlns='http://www.w3.org/2000/svg'>
              <path
                d='M36 64C51.464 64 64 51.464 64 36C64 20.536 51.464 8 36 8C20.536 8 8 20.536 8 36C8 51.464 20.536 64 36 64Z'
                fill='#146EB4'
                fill-opacity='0.15'
                stroke='#146EB4'
                stroke-width='3.5'
                stroke-miterlimit='10'
              />
              <path d='M44 31L36 23L28 31' stroke='#146EB4' stroke-width='3.2' stroke-linecap='round' stroke-linejoin='round' />
              <path d='M36 23V42.2' stroke='#146EB4' stroke-width='3.2' stroke-linecap='round' stroke-linejoin='round' />
              <path d='M54 40.2857L49.7143 36L45.4286 40.2857' stroke='#146EB4' stroke-width='2.6' stroke-linecap='round' stroke-linejoin='round' />
              <path d='M49.7143 36V46.2857' stroke='#146EB4' stroke-width='2.6' stroke-linecap='round' stroke-linejoin='round' />
              <path d='M26.5714 40.2857L22.2857 36L18 40.2857' stroke='#146EB4' stroke-width='2.6' stroke-linecap='round' stroke-linejoin='round' />
              <path d='M22.2857 36V46.2857' stroke='#146EB4' stroke-width='2.6' stroke-linecap='round' stroke-linejoin='round' />
            </svg>
          </div>
        </div>

        <div className='row d-feature__title'>
          <div className='col-sm-4'>
            <h5>Search</h5>
          </div>
          <div className='col-sm-4'>
            <h5>Select</h5>
          </div>
          <div className='col-sm-4'>
            <h5>Stand out</h5>
          </div>
        </div>

        <div className='row d-feature__description'>
          <div className='col-sm-4'>
            <p>Simply add a keyword or a term related to your business in the slogan maker search box. Wait for the magic to happen.</p>
          </div>
          <div className='col-sm-4'>
            <p>Choose from thousands of options generated by the slogan maker that fit your needs.</p>
          </div>
          <div className='col-sm-4'>
            <p>Congrats on your new slogan. It's time to win the world!</p>
          </div>
        </div>
      </div>
    </div>
  );
}

export default FeaturesSection;
